### ISSUE TITLE
[Bug]: No Changelog for 24.0.0

### ISSUE THREAD

**Issue by JensGutermuth** [nextcloud/website#21] opened 2022-05-15 10:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is no changelog published on the [changelog page](https://nextcloud.com/changelog/) on nextcloud.com for 24.0.0.

### Steps to reproduce

1. Go to the [server download page](https://nextcloud.com/install/#instructions-server). "Latest stable version" is 24.0.0.
2. Follow the link to the [changelog](https://nextcloud.com/changelog/). Latest version with a changelog entry is 23.0.4.
3. [Latest release](https://github.com/nextcloud/server/releases/latest) here on GitHub is 24.0.0 (with no description) from ten days ago.

### Expected behavior

The changelog on nextcloud.com should be updated before or very shortly after a release is made - especially a new major version. Having no changelog on the main website for the current stable version is very odd for a project as big as nextcloud - and especially considering this is clearly not an isolated instance of that. Please consider, that a new major version indicates possible breaking changes admins might want to know about before upgrading and not finding one will likely delay updates and reduce confidence in the project.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
irrelevant, see below
```

### Additional info

This happened with at least v20.0.0 (see https://github.com/nextcloud/server/issues/23219), v20.0.8 (see https://github.com/nextcloud/server/issues/25792) and 23.0.0 (see https://github.com/nextcloud/nextcloud.com/issues/1583) as well. I already reported the [same bug](https://github.com/nextcloud/nextcloud.com/issues/1647) in the nextcloud.com repository with no reaction for seven days. Also see https://github.com/nextcloud/server/issues/31198 as the "big picture" version of this.

All the info about my installation is irrelevant, as this doesn't effect my installation but the project as a whole.

**Comment by solracsf** [comment] 2022-05-16 07:19
Duplicate of https://github.com/nextcloud/nextcloud.com/issues/1647

**Closed as completed by solracsf** 2022-05-16 07:19 UTC
Labels: bug, 0. Needs triage
